import type { DocumentDomain, DocumentCategory } from "../types";

export interface CatalogMeta {
  id: string;
  name: string;
  description: string;
  domain: DocumentDomain;
  category: DocumentCategory;
  priority: "essential" | "common" | "specialized";
  tags: string[];
  primaryResources: string[];
}

/** 141 document types across business, individual, and organization domains */
export const DOCUMENT_CATALOG: CatalogMeta[] = [
  // ── BUSINESS · ESSENTIAL (20) ──
  { id: "invoice", name: "Invoice", description: "Bill for goods or services rendered", domain: "business", category: "financial", priority: "essential", tags: ["billing", "accounts-receivable"], primaryResources: ["UCC Article 2", "GAAP revenue recognition", "IRS recordkeeping"] },
  { id: "quote-estimate", name: "Quote / Estimate", description: "Price proposal before work begins", domain: "business", category: "sales", priority: "essential", tags: ["sales", "pricing"], primaryResources: ["AIA estimate standards", "RSMeans cost data"] },
  { id: "receipt", name: "Receipt", description: "Proof of payment for a transaction", domain: "business", category: "financial", priority: "essential", tags: ["payment", "pos"], primaryResources: ["IRS substantiation rules", "PCI-DSS receipt standards"] },
  { id: "purchase-order", name: "Purchase Order", description: "Official order to a vendor or supplier", domain: "business", category: "operations", priority: "essential", tags: ["procurement", "vendor"], primaryResources: ["APICS procurement standards", "UCC Article 2"] },
  { id: "service-agreement", name: "Service Agreement", description: "Contract defining scope, terms, and payment", domain: "business", category: "legal", priority: "essential", tags: ["contract", "services"], primaryResources: ["Restatement (Second) of Contracts", "UCC Article 2"] },
  { id: "nda", name: "Non-Disclosure Agreement", description: "Protect confidential business information", domain: "business", category: "legal", priority: "essential", tags: ["confidentiality", "legal"], primaryResources: ["Uniform Trade Secrets Act", "DTSA 2016"] },
  { id: "employment-offer-letter", name: "Employment Offer Letter", description: "Formal job offer with terms of employment", domain: "business", category: "hr", priority: "essential", tags: ["hiring", "hr"], primaryResources: ["FLSA", "EEOC hiring guidelines", "SHRM offer letter standards"] },
  { id: "independent-contractor-agreement", name: "Independent Contractor Agreement", description: "Engage freelancers without employee status", domain: "business", category: "hr", priority: "essential", tags: ["contractor", "1099"], primaryResources: ["IRS Form SS-8 criteria", "DOL independent contractor rule"] },
  { id: "work-order", name: "Work Order", description: "Authorize and track a specific job or task", domain: "business", category: "operations", priority: "essential", tags: ["field-service", "maintenance"], primaryResources: ["ISO 9001 work order traceability", "CMMS standards"] },
  { id: "client-intake-form", name: "Client Intake Form", description: "Collect new client information and requirements", domain: "business", category: "sales", priority: "essential", tags: ["onboarding", "crm"], primaryResources: ["CRM best practices", "GDPR/CCPA data collection"] },
  { id: "scope-of-work", name: "Scope of Work", description: "Detailed project deliverables and boundaries", domain: "business", category: "project", priority: "essential", tags: ["project", "deliverables"], primaryResources: ["PMI PMBOK", "AIA document G701"] },
  { id: "proposal", name: "Business Proposal", description: "Persuasive pitch for products or services", domain: "business", category: "sales", priority: "essential", tags: ["sales", "pitch"], primaryResources: ["APMP proposal standards", "RFP best practices"] },
  { id: "expense-report", name: "Expense Report", description: "Employee reimbursement for business expenses", domain: "business", category: "financial", priority: "essential", tags: ["reimbursement", "accounting"], primaryResources: ["IRS accountable plan rules", "GAAP expense reporting"] },
  { id: "timesheet", name: "Timesheet", description: "Track employee hours for payroll", domain: "business", category: "hr", priority: "essential", tags: ["payroll", "time-tracking"], primaryResources: ["FLSA recordkeeping", "DOL timesheet requirements"] },
  { id: "payment-reminder", name: "Payment Reminder", description: "Follow-up for overdue invoices", domain: "business", category: "financial", priority: "essential", tags: ["collections", "ar"], primaryResources: ["FDCPA (if third-party)", "UCC collection practices"] },
  { id: "terms-of-service", name: "Terms of Service", description: "Rules governing use of your product or service", domain: "business", category: "legal", priority: "essential", tags: ["policy", "website"], primaryResources: ["CISG", "EU Digital Services Act", "CCPA"] },
  { id: "privacy-policy", name: "Privacy Policy", description: "How you collect and use personal data", domain: "business", category: "compliance", priority: "essential", tags: ["policy", "gdpr"], primaryResources: ["GDPR Art. 13-14", "CCPA/CPRA", "CalOPPA"] },
  { id: "w9-request", name: "W-9 Request Form", description: "Collect vendor tax identification information", domain: "business", category: "compliance", priority: "essential", tags: ["tax", "1099"], primaryResources: ["IRS Form W-9", "IRC §6041"] },
  { id: "delivery-receipt", name: "Delivery Receipt", description: "Confirm goods were received in good condition", domain: "business", category: "operations", priority: "essential", tags: ["shipping", "logistics"], primaryResources: ["UCC Article 2-509", "Incoterms 2020"] },
  { id: "incident-report", name: "Workplace Incident Report", description: "Document accidents, injuries, or safety events", domain: "business", category: "compliance", priority: "essential", tags: ["safety", "osha"], primaryResources: ["OSHA 300/301 logs", "ISO 45001"] },

  // ── BUSINESS · COMMON (25) ──
  { id: "credit-memo", name: "Credit Memo", description: "Issue credit against a prior invoice", domain: "business", category: "financial", priority: "common", tags: ["billing", "refund"], primaryResources: ["GAAP credit memo standards"] },
  { id: "statement-of-account", name: "Statement of Account", description: "Summary of open balances for a customer", domain: "business", category: "financial", priority: "common", tags: ["billing", "ar"], primaryResources: ["GAAP AR aging standards"] },
  { id: "vendor-agreement", name: "Vendor Agreement", description: "Terms for purchasing from a supplier", domain: "business", category: "legal", priority: "common", tags: ["procurement", "vendor"], primaryResources: ["UCC Article 2", "ISDA (if applicable)"] },
  { id: "subcontractor-agreement", name: "Subcontractor Agreement", description: "Engage a subcontractor on a project", domain: "business", category: "legal", priority: "common", tags: ["construction", "contractor"], primaryResources: ["AIA A401", "ConsensusDocs 750"] },
  { id: "change-order", name: "Change Order", description: "Modify scope, price, or timeline of a project", domain: "business", category: "project", priority: "common", tags: ["construction", "project"], primaryResources: ["AIA G701 Change Directive", "PMI change control"] },
  { id: "meeting-minutes", name: "Meeting Minutes", description: "Official record of a business meeting", domain: "business", category: "governance", priority: "common", tags: ["meetings", "records"], primaryResources: ["Robert's Rules of Order", "Delaware corporate law"] },
  { id: "meeting-agenda", name: "Meeting Agenda", description: "Structured plan for an upcoming meeting", domain: "business", category: "communication", priority: "common", tags: ["meetings"], primaryResources: ["Robert's Rules of Order"] },
  { id: "performance-review", name: "Performance Review", description: "Evaluate employee performance and goals", domain: "business", category: "hr", priority: "common", tags: ["hr", "evaluation"], primaryResources: ["SHRM performance management", "EEOC evaluation guidelines"] },
  { id: "termination-letter", name: "Termination Letter", description: "Formal notice of employment separation", domain: "business", category: "hr", priority: "common", tags: ["hr", "separation"], primaryResources: ["WARN Act", "State at-will doctrine"] },
  { id: "warning-letter", name: "Employee Warning Letter", description: "Document disciplinary action or policy violation", domain: "business", category: "hr", priority: "common", tags: ["hr", "discipline"], primaryResources: ["NLRB Weingarten rights", "Progressive discipline standards"] },
  { id: "employee-handbook-acknowledgment", name: "Handbook Acknowledgment", description: "Employee confirms receipt of company policies", domain: "business", category: "hr", priority: "common", tags: ["hr", "policy"], primaryResources: ["SHRM handbook standards", "NLRB policy requirements"] },
  { id: "sop", name: "Standard Operating Procedure", description: "Step-by-step instructions for a business process", domain: "business", category: "operations", priority: "common", tags: ["process", "quality"], primaryResources: ["ISO 9001 SOP format", "FDA 21 CFR Part 211"] },
  { id: "packing-slip", name: "Packing Slip", description: "Itemized list of contents in a shipment", domain: "business", category: "operations", priority: "common", tags: ["shipping", "warehouse"], primaryResources: ["UCC shipping documents", "GS1 logistics standards"] },
  { id: "bill-of-lading", name: "Bill of Lading", description: "Legal document for freight shipment", domain: "business", category: "operations", priority: "common", tags: ["freight", "shipping"], primaryResources: ["UCC Article 7", "COGSA", "Incoterms 2020"] },
  { id: "inventory-sheet", name: "Inventory Sheet", description: "Track stock levels and product counts", domain: "business", category: "operations", priority: "common", tags: ["inventory", "warehouse"], primaryResources: ["GAAP inventory valuation", "FIFO/LIFO standards"] },
  { id: "rfp-response", name: "RFP Response", description: "Formal reply to a request for proposal", domain: "business", category: "sales", priority: "common", tags: ["sales", "government"], primaryResources: ["FAR Part 15", "APMP capture standards"] },
  { id: "project-status-report", name: "Project Status Report", description: "Update stakeholders on project progress", domain: "business", category: "project", priority: "common", tags: ["project", "reporting"], primaryResources: ["PMI status reporting", "PRINCE2 highlight reports"] },
  { id: "project-charter", name: "Project Charter", description: "Authorize and define a new project", domain: "business", category: "project", priority: "common", tags: ["project", "initiation"], primaryResources: ["PMI PMBOK Project Charter", "PRINCE2 PID"] },
  { id: "marketing-plan", name: "Marketing Plan", description: "Strategy for promoting products or services", domain: "business", category: "marketing", priority: "common", tags: ["marketing", "strategy"], primaryResources: ["AMA marketing plan framework", "SOSTAC model"] },
  { id: "press-release", name: "Press Release", description: "Official announcement to media outlets", domain: "business", category: "marketing", priority: "common", tags: ["pr", "media"], primaryResources: ["AP Stylebook", "PRSA ethics standards"] },
  { id: "customer-feedback-form", name: "Customer Feedback Form", description: "Collect customer satisfaction and reviews", domain: "business", category: "sales", priority: "common", tags: ["feedback", "csat"], primaryResources: ["NPS methodology", "ISO 10002 complaints handling"] },
  { id: "warranty-claim", name: "Warranty Claim Form", description: "Process a product warranty request", domain: "business", category: "operations", priority: "common", tags: ["warranty", "returns"], primaryResources: ["Magnuson-Moss Warranty Act", "UCC Article 2-314"] },
  { id: "return-authorization", name: "Return Merchandise Authorization", description: "Authorize and track product returns", domain: "business", category: "operations", priority: "common", tags: ["returns", "rma"], primaryResources: ["UCC return rights", "Retail industry RMA standards"] },
  { id: "collection-letter", name: "Collection Letter", description: "Demand payment on overdue accounts", domain: "business", category: "financial", priority: "common", tags: ["collections", "ar"], primaryResources: ["FDCPA", "UCC Article 9"] },
  { id: "demand-letter", name: "Demand Letter", description: "Formal pre-litigation payment or action demand", domain: "business", category: "legal", priority: "common", tags: ["legal", "collections"], primaryResources: ["State civil procedure", "ABA demand letter standards"] },

  // ── BUSINESS · SPECIALIZED (15) ──
  { id: "commercial-lease", name: "Commercial Lease Agreement", description: "Lease commercial property or space", domain: "business", category: "real-estate", priority: "specialized", tags: ["lease", "commercial"], primaryResources: ["AIR commercial lease forms", "State landlord-tenant law"] },
  { id: "equipment-rental", name: "Equipment Rental Agreement", description: "Rent equipment to or from another party", domain: "business", category: "operations", priority: "specialized", tags: ["rental", "equipment"], primaryResources: ["UCC Article 2A (leases)", "ISO equipment rental standards"] },
  { id: "partnership-agreement", name: "Partnership Agreement", description: "Define terms between business partners", domain: "business", category: "legal", priority: "specialized", tags: ["partnership", "entity"], primaryResources: ["UPA/RUPA", "State partnership statutes"] },
  { id: "board-resolution", name: "Board Resolution", description: "Formal decision by a company's board of directors", domain: "business", category: "governance", priority: "specialized", tags: ["corporate", "governance"], primaryResources: ["Delaware General Corporation Law", "Model Business Corporation Act"] },
  { id: "hipaa-baa", name: "HIPAA Business Associate Agreement", description: "Required contract for handling protected health info", domain: "business", category: "compliance", priority: "specialized", tags: ["healthcare", "hipaa"], primaryResources: ["HIPAA Privacy Rule 45 CFR 164.504", "HITECH Act"] },
  { id: "quality-control-checklist", name: "Quality Control Checklist", description: "Verify product or service meets quality standards", domain: "business", category: "operations", priority: "specialized", tags: ["quality", "inspection"], primaryResources: ["ISO 9001", "Six Sigma QC standards"] },
  { id: "training-record", name: "Employee Training Record", description: "Document completed training and certifications", domain: "business", category: "hr", priority: "specialized", tags: ["training", "compliance"], primaryResources: ["OSHA training requirements", "ISO 45001"] },
  { id: "maintenance-log", name: "Equipment Maintenance Log", description: "Track maintenance and repairs on assets", domain: "business", category: "operations", priority: "specialized", tags: ["maintenance", "cmms"], primaryResources: ["ISO 55000 asset management", "NFPA maintenance standards"] },
  { id: "balance-sheet", name: "Balance Sheet", description: "Snapshot of assets, liabilities, and equity", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "financial-statement"], primaryResources: ["GAAP ASC 210", "IFRS IAS 1"] },
  { id: "income-statement", name: "Income Statement", description: "Report revenue and expenses over a period", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "p&l"], primaryResources: ["GAAP ASC 220", "IFRS IAS 1"] },
  { id: "cash-flow-statement", name: "Cash Flow Statement", description: "Track cash inflows and outflows", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "cash-flow"], primaryResources: ["GAAP ASC 230", "IFRS IAS 7"] },
  { id: "bank-reconciliation", name: "Bank Reconciliation", description: "Match bank statement to internal records", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "reconciliation"], primaryResources: ["GAAP cash reconciliation", "SOX Section 404"] },
  { id: "ip-assignment", name: "IP Assignment Agreement", description: "Transfer intellectual property ownership", domain: "business", category: "legal", priority: "specialized", tags: ["ip", "patent"], primaryResources: ["USPTO assignment recordation", "Copyright Act §204"] },
  { id: "cease-and-desist", name: "Cease and Desist Letter", description: "Demand stop of infringing or harmful activity", domain: "business", category: "legal", priority: "specialized", tags: ["legal", "ip"], primaryResources: ["Lanham Act", "State unfair competition law"] },
  { id: "business-plan", name: "Business Plan", description: "Comprehensive plan for starting or growing a business", domain: "business", category: "project", priority: "specialized", tags: ["startup", "strategy"], primaryResources: ["SBA business plan guide", "SBIC investment criteria"] },

  // ── INDIVIDUAL · ESSENTIAL (15) ──
  { id: "resume", name: "Resume / CV", description: "Professional summary of work history and skills", domain: "individual", category: "personal", priority: "essential", tags: ["career", "job-search"], primaryResources: ["HR resume screening standards", "LinkedIn profile conventions"] },
  { id: "cover-letter", name: "Cover Letter", description: "Personalized letter accompanying a job application", domain: "individual", category: "personal", priority: "essential", tags: ["career", "job-search"], primaryResources: ["SHRM application standards", "Career services best practices"] },
  { id: "personal-budget", name: "Personal Budget", description: "Track monthly income and expenses", domain: "individual", category: "financial", priority: "essential", tags: ["budget", "personal-finance"], primaryResources: ["CFP Board budgeting standards", "50/30/20 rule framework"] },
  { id: "residential-lease", name: "Residential Lease Agreement", description: "Rent a home or apartment", domain: "individual", category: "real-estate", priority: "essential", tags: ["rental", "housing"], primaryResources: ["Uniform Residential Landlord Tenant Act", "State tenant protection laws"] },
  { id: "rental-application", name: "Rental Application", description: "Apply to rent a residential property", domain: "individual", category: "real-estate", priority: "essential", tags: ["rental", "housing"], primaryResources: ["FCRA tenant screening", "Fair Housing Act"] },
  { id: "personal-loan-agreement", name: "Personal Loan Agreement", description: "Document a loan between individuals", domain: "individual", category: "financial", priority: "essential", tags: ["loan", "personal"], primaryResources: ["State usury laws", "Promissory note standards"] },
  { id: "vehicle-bill-of-sale", name: "Vehicle Bill of Sale", description: "Transfer ownership of a vehicle", domain: "individual", category: "personal", priority: "essential", tags: ["vehicle", "sale"], primaryResources: ["State DMV title transfer requirements", "UCC Article 9"] },
  { id: "resignation-letter", name: "Resignation Letter", description: "Formally notify employer of departure", domain: "individual", category: "personal", priority: "essential", tags: ["career", "employment"], primaryResources: ["At-will employment standards", "Professional exit best practices"] },
  { id: "freelance-invoice", name: "Freelance Invoice", description: "Bill clients as an independent professional", domain: "individual", category: "financial", priority: "essential", tags: ["freelance", "billing"], primaryResources: ["IRS self-employment tax rules", "1099-NEC reporting"] },
  { id: "personal-reference-letter", name: "Personal Reference Letter", description: "Vouch for someone's character or abilities", domain: "individual", category: "personal", priority: "essential", tags: ["reference", "recommendation"], primaryResources: ["Professional reference letter conventions"] },
  { id: "complaint-letter", name: "Consumer Complaint Letter", description: "Formal complaint about a product or service", domain: "individual", category: "communication", priority: "essential", tags: ["consumer", "dispute"], primaryResources: ["FTC consumer complaint process", "State AG consumer protection"] },
  { id: "emergency-contact-sheet", name: "Emergency Contact Sheet", description: "List critical contacts and medical info", domain: "individual", category: "health", priority: "essential", tags: ["emergency", "safety"], primaryResources: ["Red Cross emergency preparedness", "HIPAA minimum necessary"] },
  { id: "home-inventory", name: "Home Inventory", description: "Document possessions for insurance claims", domain: "individual", category: "personal", priority: "essential", tags: ["insurance", "inventory"], primaryResources: ["NAIC home inventory guidelines", "Insurance claim documentation standards"] },
  { id: "permission-slip", name: "Permission Slip", description: "Parental consent for school or activity participation", domain: "individual", category: "education", priority: "essential", tags: ["school", "parental-consent"], primaryResources: ["FERPA", "State parental consent laws"] },
  { id: "personal-net-worth", name: "Personal Net Worth Statement", description: "Summary of personal assets and liabilities", domain: "individual", category: "financial", priority: "essential", tags: ["finance", "wealth"], primaryResources: ["CFP Board financial planning standards", "GAAP personal financial statements"] },

  // ── INDIVIDUAL · COMMON (15) ──
  { id: "roommate-agreement", name: "Roommate Agreement", description: "Set rules and responsibilities between roommates", domain: "individual", category: "real-estate", priority: "common", tags: ["rental", "shared-housing"], primaryResources: ["State tenancy law", "Joint tenancy conventions"] },
  { id: "babysitter-instructions", name: "Babysitter Instructions", description: "Emergency info and routines for childcare", domain: "individual", category: "personal", priority: "common", tags: ["childcare", "family"], primaryResources: ["AAP childcare safety guidelines", "Red Cross babysitting standards"] },
  { id: "pet-care-agreement", name: "Pet Care Agreement", description: "Terms for pet sitting or boarding services", domain: "individual", category: "personal", priority: "common", tags: ["pets", "care"], primaryResources: ["AVMA pet care standards", "State animal welfare laws"] },
  { id: "travel-itinerary", name: "Travel Itinerary", description: "Plan and share trip details and reservations", domain: "individual", category: "personal", priority: "common", tags: ["travel", "planning"], primaryResources: ["IATA travel documentation", "TSA travel guidelines"] },
  { id: "gift-letter", name: "Gift Letter", description: "Confirm a financial gift for mortgage or tax purposes", domain: "individual", category: "financial", priority: "common", tags: ["mortgage", "gift"], primaryResources: ["Fannie Mae gift letter requirements", "IRS gift tax rules"] },
  { id: "subscription-cancellation", name: "Subscription Cancellation Letter", description: "Cancel a recurring service or membership", domain: "individual", category: "communication", priority: "common", tags: ["cancellation", "consumer"], primaryResources: ["FTC Click-to-Cancel rule", "State auto-renewal laws"] },
  { id: "dispute-letter", name: "Credit Dispute Letter", description: "Challenge errors on a credit report", domain: "individual", category: "financial", priority: "common", tags: ["credit", "dispute"], primaryResources: ["FCRA §611", "CFPB dispute guidelines"] },
  { id: "thank-you-letter", name: "Thank You Letter", description: "Express gratitude professionally or personally", domain: "individual", category: "communication", priority: "common", tags: ["gratitude", "correspondence"], primaryResources: ["Professional correspondence standards"] },
  { id: "apology-letter", name: "Apology Letter", description: "Formally apologize for a mistake or offense", domain: "individual", category: "communication", priority: "common", tags: ["correspondence"], primaryResources: ["Conflict resolution communication standards"] },
  { id: "moving-checklist", name: "Moving Checklist", description: "Organize tasks for a residential move", domain: "individual", category: "personal", priority: "common", tags: ["moving", "planning"], primaryResources: ["USPS change of address", "FMCSA moving regulations"] },
  { id: "meal-planner", name: "Meal Planner", description: "Plan weekly meals and grocery shopping", domain: "individual", category: "personal", priority: "common", tags: ["food", "planning"], primaryResources: ["USDA Dietary Guidelines", "FDA nutrition labeling"] },
  { id: "goal-setting-worksheet", name: "Goal Setting Worksheet", description: "Define and track personal or professional goals", domain: "individual", category: "personal", priority: "common", tags: ["productivity", "planning"], primaryResources: ["SMART goals framework", "OKR methodology"] },
  { id: "medical-history-form", name: "Medical History Form", description: "Record personal health history for providers", domain: "individual", category: "health", priority: "common", tags: ["health", "medical"], primaryResources: ["HIPAA patient rights", "HL7 FHIR patient summary"] },
  { id: "school-excuse-note", name: "School Excuse Note", description: "Explain a student's absence to school", domain: "individual", category: "education", priority: "common", tags: ["school", "absence"], primaryResources: ["State compulsory attendance laws", "FERPA"] },
  { id: "side-business-ledger", name: "Side Business Ledger", description: "Track income and expenses for a side hustle", domain: "individual", category: "financial", priority: "common", tags: ["freelance", "accounting"], primaryResources: ["IRS Schedule C", "Self-employment tax rules"] },

  // ── INDIVIDUAL · SPECIALIZED (5) ──
  { id: "wedding-planning-checklist", name: "Wedding Planning Checklist", description: "Organize tasks and vendors for a wedding", domain: "individual", category: "personal", priority: "specialized", tags: ["wedding", "event"], primaryResources: ["Wedding industry planning standards"] },
  { id: "party-invitation", name: "Party Invitation", description: "Invite guests to a personal event", domain: "individual", category: "communication", priority: "specialized", tags: ["event", "invitation"], primaryResources: ["Event invitation etiquette standards"] },
  { id: "house-rules", name: "House Rules", description: "Set expectations for household members or guests", domain: "individual", category: "personal", priority: "specialized", tags: ["family", "household"], primaryResources: ["Shared living best practices"] },
  { id: "tax-deduction-tracker", name: "Tax Deduction Tracker", description: "Log deductible expenses throughout the year", domain: "individual", category: "financial", priority: "specialized", tags: ["tax", "deductions"], primaryResources: ["IRS Publication 17", "Schedule A itemized deductions"] },
  { id: "interview-prep-worksheet", name: "Interview Prep Worksheet", description: "Prepare answers and questions for job interviews", domain: "individual", category: "personal", priority: "specialized", tags: ["career", "interview"], primaryResources: ["STAR interview method", "Behavioral interview standards"] },

  // ── ORGANIZATION · ESSENTIAL (15) ──
  { id: "membership-application", name: "Membership Application", description: "Apply to join an organization or club", domain: "organization", category: "nonprofit", priority: "essential", tags: ["membership", "onboarding"], primaryResources: ["ASAE membership standards", "State nonprofit membership law"] },
  { id: "volunteer-agreement", name: "Volunteer Agreement", description: "Define expectations and liability for volunteers", domain: "organization", category: "nonprofit", priority: "essential", tags: ["volunteer", "nonprofit"], primaryResources: ["Volunteer Protection Act 1997", "Nonprofit volunteer management standards"] },
  { id: "donation-receipt", name: "Donation Receipt", description: "Acknowledge charitable contributions for tax purposes", domain: "organization", category: "nonprofit", priority: "essential", tags: ["donation", "tax"], primaryResources: ["IRS Publication 1771", "IRC §170(f)(8)"] },
  { id: "grant-application", name: "Grant Application", description: "Apply for funding from a foundation or agency", domain: "organization", category: "nonprofit", priority: "essential", tags: ["grant", "fundraising"], primaryResources: ["Grants.gov standards", "Foundation Center grant writing"] },
  { id: "annual-report", name: "Annual Report", description: "Summarize yearly activities, finances, and impact", domain: "organization", category: "nonprofit", priority: "essential", tags: ["reporting", "transparency"], primaryResources: ["IRS Form 990", "Guidestar reporting standards"] },
  { id: "board-meeting-minutes", name: "Board Meeting Minutes", description: "Official record of board of directors meetings", domain: "organization", category: "governance", priority: "essential", tags: ["board", "governance"], primaryResources: ["Robert's Rules of Order", "State nonprofit corporation law"] },
  { id: "conflict-of-interest-policy", name: "Conflict of Interest Policy", description: "Prevent and disclose conflicts among leaders", domain: "organization", category: "governance", priority: "essential", tags: ["governance", "ethics"], primaryResources: ["IRS Form 1023 COI requirements", "Sarbanes-Oxley COI standards"] },
  { id: "code-of-conduct", name: "Code of Conduct", description: "Standards of behavior for members and staff", domain: "organization", category: "governance", priority: "essential", tags: ["ethics", "policy"], primaryResources: ["ISO 37001 anti-bribery", "Nonprofit accountability standards"] },
  { id: "fundraising-letter", name: "Fundraising Letter", description: "Solicit donations from supporters", domain: "organization", category: "nonprofit", priority: "essential", tags: ["fundraising", "donors"], primaryResources: ["AFP Code of Ethical Standards", "CAN-SPAM Act"] },
  { id: "volunteer-signup-sheet", name: "Volunteer Sign-Up Sheet", description: "Register volunteers for events or programs", domain: "organization", category: "nonprofit", priority: "essential", tags: ["volunteer", "events"], primaryResources: ["Volunteer management best practices"] },
  { id: "event-planning-checklist", name: "Event Planning Checklist", description: "Organize tasks for an organizational event", domain: "organization", category: "nonprofit", priority: "essential", tags: ["events", "planning"], primaryResources: ["CIC event management standards", "NFPA event safety codes"] },
  { id: "program-evaluation-report", name: "Program Evaluation Report", description: "Assess effectiveness of an organizational program", domain: "organization", category: "nonprofit", priority: "essential", tags: ["evaluation", "impact"], primaryResources: ["CDC program evaluation framework", "Outcome measurement standards"] },
  { id: "sponsorship-proposal", name: "Sponsorship Proposal", description: "Pitch corporate sponsors for events or programs", domain: "organization", category: "nonprofit", priority: "essential", tags: ["sponsorship", "fundraising"], primaryResources: ["IEG sponsorship valuation", "Event sponsorship industry standards"] },
  { id: "budget-proposal-nonprofit", name: "Nonprofit Budget Proposal", description: "Proposed budget for programs and operations", domain: "organization", category: "financial", priority: "essential", tags: ["budget", "nonprofit"], primaryResources: ["FASB ASC 958 (nonprofit accounting)", "IRS nonprofit budget guidelines"] },
  { id: "donor-acknowledgment", name: "Donor Acknowledgment Letter", description: "Thank donors and confirm gift details", domain: "organization", category: "nonprofit", priority: "essential", tags: ["donors", "stewardship"], primaryResources: ["AFP donor bill of rights", "IRS substantiation requirements"] },

  // ── ORGANIZATION · COMMON (10) ──
  { id: "committee-charter", name: "Committee Charter", description: "Define purpose and authority of a committee", domain: "organization", category: "governance", priority: "common", tags: ["committee", "governance"], primaryResources: ["Robert's Rules committee standards", "Nonprofit governance best practices"] },
  { id: "strategic-plan", name: "Strategic Plan", description: "Long-term goals and strategies for the organization", domain: "organization", category: "governance", priority: "common", tags: ["strategy", "planning"], primaryResources: ["Balanced Scorecard", "ISO 9001 strategic planning"] },
  { id: "grant-report", name: "Grant Report to Funder", description: "Report outcomes and finances to a grant maker", domain: "organization", category: "nonprofit", priority: "common", tags: ["grant", "reporting"], primaryResources: ["OMB Uniform Guidance 2 CFR 200", "Foundation reporting standards"] },
  { id: "in-kind-donation-receipt", name: "In-Kind Donation Receipt", description: "Acknowledge non-cash charitable contributions", domain: "organization", category: "nonprofit", priority: "common", tags: ["donation", "in-kind"], primaryResources: ["IRS Publication 561", "IRC §170"] },
  { id: "event-sponsorship-agreement", name: "Event Sponsorship Agreement", description: "Contract with a sponsor for an event", domain: "organization", category: "nonprofit", priority: "common", tags: ["sponsorship", "events"], primaryResources: ["IEG sponsorship agreement standards"] },
  { id: "community-newsletter", name: "Community Newsletter", description: "Regular update to members and community", domain: "organization", category: "communication", priority: "common", tags: ["newsletter", "communication"], primaryResources: ["CAN-SPAM Act", "Newsletter industry standards"] },
  { id: "sports-team-waiver", name: "Sports Team Waiver", description: "Liability release for athletic participation", domain: "organization", category: "nonprofit", priority: "common", tags: ["sports", "waiver"], primaryResources: ["State recreational immunity statutes", "Assumption of risk doctrine"] },
  { id: "hoa-rules-acknowledgment", name: "HOA Rules Acknowledgment", description: "Confirm understanding of HOA rules and bylaws", domain: "organization", category: "governance", priority: "common", tags: ["hoa", "community"], primaryResources: ["State HOA statutes", "UCIOA (Uniform Common Interest Ownership Act)"] },
  { id: "whistleblower-policy", name: "Whistleblower Policy", description: "Protect and encourage reporting of misconduct", domain: "organization", category: "governance", priority: "common", tags: ["ethics", "compliance"], primaryResources: ["Sarbanes-Oxley §301", "IRS Form 990 whistleblower requirements"] },
  { id: "fund-allocation-report", name: "Fund Allocation Report", description: "Show how funds are distributed across programs", domain: "organization", category: "financial", priority: "common", tags: ["finance", "transparency"], primaryResources: ["FASB ASC 958 functional expenses", "Charity Navigator standards"] },

  // ── BUSINESS · ADDITIONAL (10) ──
  { id: "accounts-payable-voucher", name: "Accounts Payable Voucher", description: "Authorize payment to a vendor with GL coding", domain: "business", category: "financial", priority: "essential", tags: ["accounting", "ap", "voucher"], primaryResources: ["GAAP accounts payable", "SOX disbursement controls"] },
  { id: "journal-entry", name: "Journal Entry", description: "Record debits and credits for general ledger posting", domain: "business", category: "financial", priority: "essential", tags: ["accounting", "gl", "bookkeeping"], primaryResources: ["GAAP double-entry bookkeeping", "ASC 235 accounting policies"] },
  { id: "petty-cash-voucher", name: "Petty Cash Voucher", description: "Track small cash disbursements from petty cash fund", domain: "business", category: "financial", priority: "common", tags: ["accounting", "petty-cash"], primaryResources: ["GAAP imprest petty cash", "Internal control over cash"] },
  { id: "sales-order", name: "Sales Order", description: "Confirm customer order before fulfillment and invoicing", domain: "business", category: "sales", priority: "essential", tags: ["sales", "order-management"], primaryResources: ["Order-to-cash process", "GAAP revenue recognition"] },
  { id: "contract-amendment", name: "Contract Amendment", description: "Modify terms of an existing agreement", domain: "business", category: "legal", priority: "common", tags: ["contract", "amendment"], primaryResources: ["Restatement (Second) of Contracts §2-209", "UCC modification rules"] },
  { id: "employee-onboarding-checklist", name: "Employee Onboarding Checklist", description: "Track new hire paperwork, IT setup, and orientation tasks", domain: "business", category: "hr", priority: "common", tags: ["onboarding", "hr"], primaryResources: ["SHRM onboarding standards", "I-9 verification requirements"] },
  { id: "job-description", name: "Job Description", description: "Define role responsibilities, qualifications, and reporting", domain: "business", category: "hr", priority: "common", tags: ["hiring", "hr"], primaryResources: ["EEOC job classification", "FLSA exempt/non-exempt criteria"] },
  { id: "customer-credit-application", name: "Customer Credit Application", description: "Evaluate creditworthiness before extending payment terms", domain: "business", category: "financial", priority: "common", tags: ["credit", "ar"], primaryResources: ["FCRA business credit reporting", "UCC Article 9 security interests"] },
  { id: "vendor-registration-form", name: "Vendor Registration Form", description: "Collect W-9, banking, and compliance info from new vendors", domain: "business", category: "operations", priority: "common", tags: ["vendor", "procurement"], primaryResources: ["IRS W-9", "OFAC vendor screening"] },
  { id: "safety-inspection-checklist", name: "Safety Inspection Checklist", description: "Document workplace safety walkthrough findings", domain: "business", category: "compliance", priority: "common", tags: ["safety", "osha"], primaryResources: ["OSHA general duty clause", "ISO 45001 inspection"] },

  // ── BUSINESS · SPECIALIZED ADDITIONAL (5) ──
  { id: "contract-renewal-notice", name: "Contract Renewal Notice", description: "Notify parties of upcoming contract renewal or expiration", domain: "business", category: "legal", priority: "specialized", tags: ["contract", "renewal"], primaryResources: ["Contract renewal best practices", "Auto-renewal disclosure laws"] },
  { id: "accounts-receivable-aging", name: "Accounts Receivable Aging Report", description: "Categorize outstanding customer balances by age bucket", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "ar", "collections"], primaryResources: ["GAAP AR allowance methodology", "ASC 310 credit losses"] },
  { id: "1099-summary", name: "1099 Contractor Summary", description: "Track payments to independent contractors for year-end 1099 filing", domain: "business", category: "compliance", priority: "specialized", tags: ["tax", "1099"], primaryResources: ["IRS Form 1099-NEC", "IRC §6041 reporting thresholds"] },
  { id: "asset-disposal-form", name: "Asset Disposal Form", description: "Document retirement or sale of fixed assets", domain: "business", category: "financial", priority: "specialized", tags: ["accounting", "fixed-assets"], primaryResources: ["GAAP ASC 360 asset disposal", "IRS Form 4797"] },
  { id: "inter-office-memo", name: "Inter-Office Memo", description: "Internal communication between departments or staff", domain: "business", category: "communication", priority: "specialized", tags: ["internal", "memo"], primaryResources: ["Business communication standards"] },

  // ── INDIVIDUAL · ADDITIONAL (3) ──
  { id: "power-of-attorney", name: "Power of Attorney", description: "Authorize someone to act on your behalf in legal or financial matters", domain: "individual", category: "legal", priority: "common", tags: ["legal", "authorization"], primaryResources: ["Uniform Power of Attorney Act", "State POA statutes"] },
  { id: "lease-renewal-request", name: "Lease Renewal Request", description: "Request to extend a residential lease term", domain: "individual", category: "real-estate", priority: "common", tags: ["rental", "lease"], primaryResources: ["State landlord-tenant law", "Lease renewal notice periods"] },
  { id: "contractor-agreement-personal", name: "Home Contractor Agreement", description: "Hire a contractor for home improvement or repair work", domain: "individual", category: "personal", priority: "common", tags: ["contractor", "home"], primaryResources: ["State contractor licensing", "Mechanic's lien laws"] },

  // ── ORGANIZATION · ADDITIONAL (5) ──
  { id: "capital-campaign-plan", name: "Capital Campaign Plan", description: "Plan and track a major fundraising capital campaign", domain: "organization", category: "nonprofit", priority: "common", tags: ["fundraising", "capital-campaign"], primaryResources: ["AFP capital campaign standards", "Nonprofit fundraising ethics"] },
  { id: "volunteer-hours-log", name: "Volunteer Hours Log", description: "Track volunteer time for programs and grant reporting", domain: "organization", category: "nonprofit", priority: "common", tags: ["volunteer", "tracking"], primaryResources: ["Independent Sector volunteer value", "Grant volunteer match requirements"] },
  { id: "advisory-board-agreement", name: "Advisory Board Agreement", description: "Define role and expectations for advisory board members", domain: "organization", category: "governance", priority: "common", tags: ["advisory", "governance"], primaryResources: ["Nonprofit advisory board best practices", "Fiduciary duty standards"] },
  { id: "program-budget", name: "Program Budget", description: "Detailed budget for a specific organizational program", domain: "organization", category: "financial", priority: "common", tags: ["budget", "program"], primaryResources: ["FASB ASC 958 program reporting", "Grant budget line-item standards"] },
  { id: "audit-preparation-checklist", name: "Audit Preparation Checklist", description: "Prepare documents and schedules for an independent audit", domain: "organization", category: "compliance", priority: "specialized", tags: ["audit", "nonprofit"], primaryResources: ["AICPA nonprofit audit guide", "Single Audit Act 2 CFR 200"] },
];
